# Generated by Django 3.1.2 on 2020-10-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquirrelDetails',
            fields=[
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('Unique_Squirrel_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Hectare', models.CharField(max_length=3)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('Date', models.CharField(max_length=8)),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=10, null=True)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], max_length=10, null=True)),
                ('Highlight_Fur_Color', models.CharField(max_length=50)),
                ('Combination_of_Primary_and_Highlight_Color', models.CharField(max_length=50)),
                ('Color_notes', models.CharField(max_length=50)),
                ('Location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=20, null=True)),
                ('Above_Ground_Sighter_Measurement', models.CharField(max_length=10)),
                ('Specific_Location', models.CharField(max_length=50)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_Activities', models.CharField(max_length=50)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twitches', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
                ('Other_Interactions', models.CharField(max_length=50)),
                ('Lat_Long', models.CharField(max_length=50)),
            ],
        ),
    ]
