# Generated by Django 3.1.2 on 2020-10-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirreldetails',
            name='Latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
