# Generated by Django 3.1.2 on 2020-10-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelapp', '0003_remove_squirreldetails_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirreldetails',
            name='Longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
    ]
