# Generated by Django 3.1.2 on 2020-10-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelapp', '0004_squirreldetails_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirreldetails',
            name='Longitude',
            field=models.CharField(max_length=20),
        ),
    ]
