# Generated by Django 3.1.2 on 2020-10-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelapp', '0005_auto_20201019_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirreldetails',
            name='Longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
