# Generated by Django 3.1.2 on 2020-10-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelapp', '0006_auto_20201019_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirreldetails',
            name='Hectare_Squirrel_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Above_Ground_Sighter_Measurement',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', '')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Approaches',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Chasing',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Climbing',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Color_notes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Combination_of_Primary_and_Highlight_Color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Eating',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Foraging',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Hectare',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Highlight_Fur_Color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Indifferent',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Kuks',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Lat_Long',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Moans',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Other_Activities',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Other_Interactions',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Quaas',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Running',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Runs_from',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Specific_Location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Tail_flags',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Tail_twitches',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='squirreldetails',
            name='Unique_Squirrel_ID',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
